# Check https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
image: rafaat/java-gradle-mysql:latest

pipelines:
  default:
    - step:
        script:
          - export JAVA_HOME=/usr/lib/jvm/java-1.8.0
          - mysql_install_db --user=mysql --basedir=/usr/ --ldata=/var/lib/mysql/ &
          - sleep 30
          - mysqld           --user=mysql --basedir=/usr/ --ldata=/var/lib/mysql/ &
          - sleep 30
          - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS xipli;'
          - ./gradlew clean flywayClean flywayMigrate test build rpm
