# Check https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
image: rafaat/java-gradle-mysql:latest

pipelines:
  default:
    - step:
        script:
          - export JAVA_HOME=/usr/lib/jvm/java-1.8.0
          - ./gradlew clean flywayClean flywayMigrate test build rpm
