# Check https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
image: rafaat/java-gradle-mysql:latest

pipelines:
  default:
    - step:
        script:
          - /usr/libexec/mysqld --user=mysql --basedir=/usr/ &
          - sleep 10
          - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS xipli;'
          - ./gradlew clean flywayClean flywayMigrate test build rpm
