Vagrant.configure(2) do |config|

  config.vm.box = "centos/6"
  config.vm.network "forwarded_port", guest: 8888, host: 8889
  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder "../.", "/coffee_api"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "coffee_api"
    vb.gui = false
    vb.memory = "1024"
  end

  config.ssh.insert_key = false
  config.ssh.keys_only = false
  config.ssh.paranoid = false

  config.vm.provision :shell, path: "provision.sh"

end
