ALTER TABLE `xipli`.`XipliUser`
CHANGE COLUMN `XipliXipliUserID` `UserID` INT(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `xipli`.`XipliUser`
DROP COLUMN `Usercol`,
CHANGE COLUMN `FirstName` `FirstName` VARCHAR(250) NOT NULL ,
CHANGE COLUMN `LastName` `LastName` VARCHAR(250) NULL DEFAULT NULL ,
CHANGE COLUMN `PhoneNo` `Phone` VARCHAR(45) NULL DEFAULT NULL ,
CHANGE COLUMN `Password` `Password` VARCHAR(255) NOT NULL ,
CHANGE COLUMN `ProviderXipliUserID` `ProviderUserID` VARCHAR(45) NULL DEFAULT NULL ,
ADD COLUMN `PasswordSalt` BINARY(64) NOT NULL AFTER `Active`,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`UserID`);



ALTER TABLE `xipli`.`XipLiOrder`
CHANGE COLUMN `XipLiOrderID` `OrderID` INT(11) NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `XipliXipliUserID` `UserID` INT(11) NOT NULL ,
CHANGE COLUMN `OrderBarCode` `OrderBarCode` VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE `xipli`.`UserRole`
DROP COLUMN `UserRoleID`,
CHANGE COLUMN `XipliUserID` `UserID` INT(11) NOT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`UserID`, `Role`);

ALTER TABLE `xipli`.`ShopUser`
CHANGE COLUMN `XipliUserID` `UserID` INT(11) NOT NULL ;


ALTER TABLE `xipli`.`Shop`
CHANGE COLUMN `latitude` `Latitude` DECIMAL(20,4) NULL DEFAULT NULL ;

ALTER TABLE `xipli`.`ItemOption`
CHANGE COLUMN `itemOptionID` `ItemOptionID` INT(11) NOT NULL AUTO_INCREMENT ;
