
ALTER TABLE `xipli`.`XipLiOrder`
CHANGE COLUMN `XipLiOrderID` `OrderID` INT(11) NOT NULL AUTO_INCREMENT ,
CHANGE COLUMN `XipliXipliUserID` `UserID` INT(11) NOT NULL ,
CHANGE COLUMN `OrderBarCode` `OrderBarCode` VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE `xipli`.`UserRole`
DROP COLUMN `UserRoleID`,
CHANGE COLUMN `XipliUserID` `UserID` INT(11) NOT NULL ,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`UserID`, `Role`);

ALTER TABLE `xipli`.`ShopUser`
CHANGE COLUMN `XipliUserID` `UserID` INT(11) NOT NULL ;


ALTER TABLE `xipli`.`Shop`
CHANGE COLUMN `latitude` `Latitude` DECIMAL(20,4) NULL DEFAULT NULL ;

ALTER TABLE `xipli`.`ItemOption`
CHANGE COLUMN `itemOptionID` `ItemOptionID` INT(11) NOT NULL AUTO_INCREMENT ;
